on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Automatic Release Workflow

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.0.3
      with:
        go-version: 1.15
      id: go_setup

    - name: Check out Code
      uses: actions/checkout@v2.1.1

    - name: Run Tests
      run: |
        make test

    - name: Build Release
      run: |
        ./release.sh i3status-title-on-bar

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true

    - name: Upload Release Asset - i3status-title-on-bar-linux_amd64
      id: upload-release-asset-i3status-title-on-bar-linux_amd64
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/i3status-title-on-bar-linux_amd64
        asset_name: i3status-title-on-bar-linux_amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset - i3status-title-on-bar-linux_arm
      id: upload-release-asset-i3status-title-on-bar-linux_arm
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/i3status-title-on-bar-linux_arm
        asset_name: i3status-title-on-bar-linux_arm
        asset_content_type: application/octet-stream

    - name: Upload Release Asset - i3status-title-on-bar-linux_arm64
      id: upload-release-asset-i3status-title-on-bar-linux_arm64
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/i3status-title-on-bar-linux_arm64
        asset_name: i3status-title-on-bar-linux_arm64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset - sha256sums
      id: upload-release-asset-sha256sums
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/sha256sums
        asset_name: sha256sums
        asset_content_type: text/plain
