on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Automatic Release Workflow

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-22.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: 1.24
      id: go_setup

    - name: Check out Code
      uses: actions/checkout@v4.2.2

    - name: Run Tests
      run: |
        make test

    - name: Build Release
      run: |
        ./release.sh i3status-title-on-bar

    - name: Upload Release Assets
      id: upload-release-assets
      uses: softprops/action-gh-release@v2.3.2
      with:
        name: Release ${{ github.ref }}
        draft: true
        prerelease: true
        fail_on_unmatched_files: true
        files: |
          ./build/i3status-title-on-bar-linux_amd64
          ./build/i3status-title-on-bar-linux_arm
          ./build/i3status-title-on-bar-linux_arm64
          ./build/sha256sums
